### ISSUE TITLE
Python Lists are not Linked Lists

### ISSUE THREAD

**Issue by rafadaguiar** [donnemartin/interactive-coding-challenges#27]
In some of the challenges (ex: hash_map), Python Lists are referred as being the same as linked lists. 
In fact, Python Lists are implemented using arrays of pointers (that explains random access and O(1) appends).

You can see this FAQ: https://docs.python.org/2/faq/design.html#how-are-lists-implemented 
Or a short explanation on: http://stackoverflow.com/questions/3917574/how-is-pythons-list-implemented

**Comment by donnemartin** [comment]
Hi Rafael,

Nice catch on hash_map, thanks for the bug report!  In the constraints section I probably should say collision resolution with a 'chaining' method instead of 'linked list'.  I'll put in a fix, unless you'd like to submit a pull request :)

>In some of the challenges (ex: hash_map)

The way this is worded, am I correct in interpreting there are other areas with the same issue?  I looked through the other challenges and couldn't find another instance.  I might have missed another case.

-Donne

**Comment by rafadaguiar** [comment]
Hi Donne,

Chaining sounds much better! I'll submit the pull request later today.

I haven't looked the entire repo yet, but so far this was the only occurrence.

**Comment by donnemartin** [comment]
Sounds good thanks Rafael.

**Comment by donnemartin** [comment]
Fixed with #28.
